server:
  port: '9096'
  host: 'http://localhost:9096'
spring:
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb # jdbc:h2:file:/data/demo if persistence is required for file
    username: root
    password: demo
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-j8ajv706.us.auth0.com/
  websecurity:
    debug: true

auth0:
  audience: http://localhost:9096/api

springdoc:
  swagger-ui:
    path: swagger-ui.html

logging:
  level:
    org:
      springframework:
        security: DEBUG

cucumbertest:
  auth:
    client-id: L8XRJjXgjJqsrUCcELtVb5m46KqWgLlf
    client-secret: 5PglHF_jc5v-81fzlJcOTM2YZ2iABNYAuekfO_WR3W4IHKN0-7yxPqcbdHO0LI65
    token-url: https://dev-j8ajv706.us.auth0.com/oauth/token
    audience: http://localhost:9096/api